// src/security/roles.js

import { PERMISSIONS } from './permissions'

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.MANAGE_GURU,
    PERMISSIONS.MANAGE_SISWA,
    PERMISSIONS.MANAGE_KELAS,
    PERMISSIONS.MANAGE_JADWAL,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.EDIT_GRADES,

    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.EDIT_ATTENDANCE,

    PERMISSIONS.VIEW_SCHEDULE,

    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.EDIT_ANNOUNCEMENTS,
  ],

  guru: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.EDIT_GRADES,

    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.EDIT_ATTENDANCE,

    PERMISSIONS.VIEW_SCHEDULE,

    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.EDIT_ANNOUNCEMENTS, // nanti dicek lagi di service kalau butuh “hanya miliknya”
  ],

  siswa: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_SCHEDULE,

    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],

  ortu: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_SCHEDULE,

    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],
}
